feat: Custom Encoder & Decoder
GoodRequest/GoodNetworking pull request #1
Opened 2023-03-14 14:52 UTC by matusklasovity

2023-03-14 15:34 UTC, plajdo commented on Sources/GoodNetworking/CodableExtensions.swift
> +//  DepoSwiftExtensions
I'd fix the file headers (in all files) considering this is now a public library

2023-03-14 15:35 UTC, plajdo commented on Sources/GoodNetworking/CodableExtensions.swift
> +    /// - Returns: `Data` representation of the `GREncodable` object.
`GREncodable` does not exist anymore though :/

2023-03-14 15:40 UTC, plajdo commented on Sources/Mockable/Mockabe.swift
this file has a typo in its name - `Mockabe`

2023-03-14 15:41 UTC, plajdo commented on Tests/GoodNetworkingTests/DateDecodingTest.swift
> +//  File.swift
there is a lot of whitespace in this file, is it intentional?

2023-03-14 15:46 UTC, plajdo commented on Sources/GoodNetworking/CodableExtensions.swift
> +    }
This computed property seems to be a duplicate of the function below it. The only difference is the encoder used. Is there any use case for that function where you'd need two custom encoders, one provided as a function parameter and the second as an overridden property?

Either way, I'd make this computed property to at least call the function below instead of duplicate implementation.

2023-03-14 15:48 UTC, plajdo commented on Sources/GoodNetworking/DataRequestExtensions.swift
> +    /// - Returns:               The `DataResponsePublisher`.
Just to be sure - is the documentation up to date in these functions?

2023-03-14 16:43 UTC, andrej-jasso commented on Sources/GoodNetworking/CodableExtensions.swift
> +    /// - Returns: `Data` representation of the `GREncodable` object.
@matusklasovity  prosimta pozri dokumentaciu a najdi zmienky GREncodable GRDecodable v projekte a nahrad ich prosimta ;)

2023-03-14 16:46 UTC, andrej-jasso commented on Tests/GoodNetworkingTests/DateDecodingTest.swift
> +//  File.swift
@matusklasovity ked vytvoris subor v Packag-i bohuzial pomenovanie tam neni automaticky z file wizardu pretoze akonahle vytvoris subor je vytvoreny a uz ho iba nasledne premenuvavas. Ale v hlavicke vzdy ostava File.swift a musis to zmenit

2023-03-14 16:47 UTC, andrej-jasso commented on Sources/GoodNetworking/DataRequestExtensions.swift
> +    /// - Returns:               The `DataResponsePublisher`.
Should be

2023-03-14 16:51 UTC, andrej-jasso requested changes

2023-03-14 16:51 UTC, andrej-jasso commented on Sources/GoodNetworking/DataRequestExtensions.swift
> +    func goodify<T: Decodable & WithCustomDecoder>(
I would add decoder in all goodify functions as a parameter with default value. 

cc: @plajdo

2023-03-16 13:23 UTC, plajdo requested changes

2023-03-16 13:23 UTC, plajdo commented on Sources/GoodNetworking/DataRequestExtensions.swift
> +            decoder: JSONDecoder(),
is `decoder` parameter required, when the implementation seems to create a new instance of `JSONDecoder` every time anyways?

2023-03-16 13:23 UTC, plajdo commented on Sources/GoodNetworking/GREndPointManagerProtocol.swift
> +//  GREndPointManagerProtocol.swift
`Endpoint` should not be capitalized since it's just one word

2023-03-16 20:14 UTC, andrej-jasso requested changes
Skus si to este prejst ci to nevieme predsa skratit ten zapis. Toto mi pride dost zdlhavy zapis

2023-03-16 20:14 UTC, andrej-jasso commented on Tests/GoodNetworkingTests/DateDecodingTest.swift
> +        static var decoder: JSONDecoder {
Trocha som sa nad tym zamyslal a vychadza mi ze mozno by bolo krajsie zaobalit tu strategiu.
Vies to aplikovat ako extension na WithCustomDecoder a zasa budeme mat ako predtym cez override. To mi prislo krajsie ako toto riesenie

2023-03-17 12:50 UTC, andrej-jasso approved these changes

2023-03-18 14:29 UTC, plajdo approved these changes

2023-03-18 14:29 UTC, merged